[options]
    UseSyslog
    Interface = eth0

[openSSH]
    sequence    = 1234,5678,9012
    seq_timeout = 5
    # -I INPUT 1 puts this rule at the very top
    command     = /sbin/iptables -I INPUT 1 -s %IP% -p tcp --dport 2222 -j ACCEPT
    tcpflags    = syn

[closeSSH]
    sequence    = 9012,5678,1234
    seq_timeout = 5
    # -D INPUT deletes the EXACT rule created above
    command     = /sbin/iptables -D INPUT -s %IP% -p tcp --dport 2222 -j ACCEPT
    tcpflags    = syn